// <auto-generated />
using ConsoleApp13;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp13.Migrations
{
    [DbContext(typeof(MidtermContext))]
    [Migration("20201018103245_Added_Point_Field")]
    partial class Added_Point_Field
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleApp13.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Tom Malaki"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Nanuka Gomareli"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Niko Nagervadze"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Sandro Begiashvili"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Neo Reeves"
                        });
                });

            modelBuilder.Entity("ConsoleApp13.Models.StudentSubject", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubjects");
                });

            modelBuilder.Entity("ConsoleApp13.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SubjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SubjectName = "Maths"
                        },
                        new
                        {
                            Id = 5,
                            SubjectName = "Biology"
                        },
                        new
                        {
                            Id = 2,
                            SubjectName = "Chemistry"
                        },
                        new
                        {
                            Id = 3,
                            SubjectName = "Physics"
                        },
                        new
                        {
                            Id = 4,
                            SubjectName = "Art"
                        });
                });

            modelBuilder.Entity("ConsoleApp13.Models.StudentSubject", b =>
                {
                    b.HasOne("ConsoleApp13.Models.Student", "Student")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp13.Models.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
